### ISSUE TITLE
node postinstall.js error

### ISSUE THREAD

**Issue by nroe** [igorklopov/enclose#108]
```
$ sudo npm install -g enclose
/usr/bin/enclose -> /usr/lib/node_modules/enclose/bin/enclose.js

> enclose@2.1.0 postinstall /usr/lib/node_modules/enclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v0.12.14-linux-x86-7bee6a7 ...
/usr/lib/node_modules/enclose/postinstall.js:165
    throw error;
    ^

Error: socket hang up
    at createHangUpError (_http_client.js:250:15)
    at TLSSocket.socketOnEnd (_http_client.js:342:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Linux 2.6.32-573.26.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "enclose"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! enclose@2.1.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the enclose@2.1.0 postinstall script 'node postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the enclose package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs enclose
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls enclose
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nroe/npm-debug.log
```

```
$npm bugs enclose
npm ERR! Linux 2.6.32-573.26.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "bugs" "enclose"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! path xdg-open
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn xdg-open

npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nroe/npm-debug.log
```

```
$cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'bugs', 'enclose' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose config Skipping project config: /home/nroe/.npmrc. (matches userconfig)
5 silly fetchPackageMetaData enclose
6 silly fetchNamedPackageData enclose
7 silly mapToRegistry name enclose
8 silly mapToRegistry using default registry
9 silly mapToRegistry registry https://registry.npmjs.org/
10 silly mapToRegistry data Result {
10 silly mapToRegistry   raw: 'enclose',
10 silly mapToRegistry   scope: null,
10 silly mapToRegistry   name: 'enclose',
10 silly mapToRegistry   rawSpec: '',
10 silly mapToRegistry   spec: 'latest',
10 silly mapToRegistry   type: 'tag' }
11 silly mapToRegistry uri https://registry.npmjs.org/enclose
12 verbose request uri https://registry.npmjs.org/enclose
13 verbose request no auth needed
14 info attempt registry request try #1 at 14:21:38
15 verbose request id 0698605c3a42e4dd
16 verbose etag "7HHUIU09ZMF5BX4ZY0TTFNYR7"
17 http request GET https://registry.npmjs.org/enclose
18 http 304 https://registry.npmjs.org/enclose
19 verbose headers { date: 'Mon, 04 Jul 2016 06:21:39 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   'cache-control': 'max-age=300',
19 verbose headers   etag: '"7HHUIU09ZMF5BX4ZY0TTFNYR7"',
19 verbose headers   age: '129',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-served-by': 'cache-lcy1125-LCY',
19 verbose headers   'x-cache': 'HIT',
19 verbose headers   'x-cache-hits': '1',
19 verbose headers   'x-timer': 'S1467613299.268069,VS0,VE0',
19 verbose headers   vary: 'Accept-Encoding' }
20 silly get cb [ 304,
20 silly get   { date: 'Mon, 04 Jul 2016 06:21:39 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     'cache-control': 'max-age=300',
20 silly get     etag: '"7HHUIU09ZMF5BX4ZY0TTFNYR7"',
20 silly get     age: '129',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-lcy1125-LCY',
20 silly get     'x-cache': 'HIT',
20 silly get     'x-cache-hits': '1',
20 silly get     'x-timer': 'S1467613299.268069,VS0,VE0',
20 silly get     vary: 'Accept-Encoding' } ]
21 verbose etag https://registry.npmjs.org/enclose from cache
22 verbose get saving enclose to /home/nroe/.npm/registry.npmjs.org/enclose/.cache.json
23 verbose correctMkdir /home/nroe/.npm correctMkdir not in flight; initializing
24 silly bugs url https://github.com/igorklopov/enclose/issues
25 verbose stack Error: spawn xdg-open ENOENT
25 verbose stack     at exports._errnoException (util.js:1007:11)
25 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
25 verbose stack     at onErrorNT (internal/child_process.js:348:16)
25 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
25 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
26 verbose cwd /home/nroe
27 error Linux 2.6.32-573.26.1.el6.x86_64
28 error argv "/usr/bin/node" "/usr/bin/npm" "bugs" "enclose"
29 error node v6.2.1
30 error npm  v3.9.3
31 error path xdg-open
32 error code ENOENT
33 error errno ENOENT
34 error syscall spawn xdg-open
35 error enoent spawn xdg-open ENOENT
36 error enoent spawn xdg-open ENOENT
36 error enoent This is most likely not a problem with npm itself
36 error enoent and is related to npm not being able to find a file.
37 verbose exit [ 1, true ]
```

**Comment by BurakDev** [comment]
Maybe a network issue. (socket hang up)

**Comment by davidwr** [comment]
`$ npm install enclose

> enclose@1.3.1 postinstall C:\Desenvolvimento\manager_edoc_saas\monitorador\node_modules\enclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v0.12.10-win32-aad2171.exe ...
C:\Desenvolvimento\manager_edoc_saas\monitorador\node_modules\enclose\postinstall.js:130
    throw error;
    ^

Error: Status code is 403, enclose-v0.12.10-win32-aad2171.exe
    at C:\Desenvolvimento\manager_edoc_saas\monitorador\node_modules\enclose\postinstall.js:71:18
    at C:\Desenvolvimento\manager_edoc_saas\monitorador\node_modules\enclose\postinstall.js:65:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "enclose"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! enclose@1.3.1 postinstall: `node postinstall.js`
npm ERR! Exit status 1`

I'm having this issue, maybe is related.
Can't download enclose...

Platform: Windows 10 x64

**Comment by alexisfrjp** [comment]
I get the same issue, I am connected behind a company proxy.
How can I solve it ?

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues

**Comment by Elmue** [comment]
zeit/pkg does not work at all.
