### ISSUE TITLE
Cannot build app on ARM

### ISSUE THREAD

**Issue by michelem09** [igorklopov/enclose#114]
I have built this app on a Macbook without any problem. On a Raspberry (RPI3, ARMv7 Processor rev 4 (v7l)) I got this:

```
TypeError: Method Uint8Array.length called on incompatible receiver [object Object]
    at Buffer.get length (native)
    at console./thebox/root/enclose-inside/lib/generate.js.module.exports (e:0)
    at e:0
    at fn (/thebox/root/enclose-inside/node_modules/async/lib/async.js:746:34)
    at /thebox/root/enclose-inside/node_modules/async/lib/async.js:1213:16
    at /thebox/root/enclose-inside/node_modules/async/lib/async.js:166:37
    at /thebox/root/enclose-inside/node_modules/async/lib/async.js:706:43
    at /thebox/root/enclose-inside/node_modules/async/lib/async.js:167:37
    at /thebox/root/enclose-inside/node_modules/async/lib/async.js:1209:30
    at /thebox/root/enclose-inside/node_modules/async/lib/async.js:52:16
```

I tried with Async 1.5.x and 2.x but it doesn't change.
Any ideas?

**Comment by michelem09** [comment]
That's weird, in a RPI2 I got this:

```
undefined:0
TypeError: Cannot read property 'toString' of null
    at ChildProcess.<anonymous> (e:0)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
