### ISSUE TITLE
rpio module doesn't work

### ISSUE THREAD

**Issue by scramble45** [igorklopov/enclose#136]
**Using:** enclose@2.2.0 full version / Node v6.4.0

[https://www.npmjs.com/package/rpio](https://www.npmjs.com/package/rpio)

````
/thebox/node_code/node_modules/bindings/bindings.js:88
  err = new Error('Could not locate the bindings file. Tried:\n'
        ^

Error: Could not locate the bindings file. Tried:
 → /thebox/node_code/build/rpio.node
 → /thebox/node_code/build/Debug/rpio.node
 → /thebox/node_code/build/Release/rpio.node
 → /thebox/node_code/out/Debug/rpio.node
 → /thebox/node_code/Debug/rpio.node
 → /thebox/node_code/out/Release/rpio.node
 → /thebox/node_code/Release/rpio.node
 → /thebox/node_code/build/default/rpio.node
 → /thebox/node_code/compiled/6.3.1/linux/arm/rpio.node
    at bindings (/thebox/node_code/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/thebox/node_code/node_modules/rpio/lib/rpio.js:17:34)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
````

> It would be really helpful if we could get a GPIO library that works with the raspberry pi and enclose.

**Comment by igorklopov** [comment]
Please ensure that your system Node.js version is same major as enclosed project runtime.
Simply place `console.log(process.versions);` as the first line in your project.

**Comment by scramble45** [comment]
So we downgraded to Node 6.3.1, uninstalled the rpio library reinstalled it then re-enclosed the code:

````
$ sudo ./gpio_rpio
{ http_parser: '2.7.0',
  node: '6.3.1',
  v8: '5.0.71.57',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h',
  enclose: '2.2.0' }
/thebox/node_code/node_modules/bindings/bindings.js:88
  err = new Error('Could not locate the bindings file. Tried:\n'
        ^

Error: Could not locate the bindings file. Tried:
 → /thebox/node_code/build/rpio.node
 → /thebox/node_code/build/Debug/rpio.node
 → /thebox/node_code/build/Release/rpio.node
 → /thebox/node_code/out/Debug/rpio.node
 → /thebox/node_code/Debug/rpio.node
 → /thebox/node_code/out/Release/rpio.node
 → /thebox/node_code/Release/rpio.node
 → /thebox/node_code/build/default/rpio.node
 → /thebox/node_code/compiled/6.3.1/linux/arm/rpio.node
    at bindings (/thebox/node_code/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/thebox/node_code/node_modules/rpio/lib/rpio.js:17:34)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
````

**node version:** 
````
$ node --version
v6.3.1
````

**Comment by igorklopov** [comment]
Also place `rpio.node` code file to the same directory as main executable `gpio_rpio`

**Comment by serkanp** [comment]
put the rpio.node file to the same folder with your enclosed app..

**Comment by scramble45** [comment]
Worked great guys, thanks Igor & serkanp.
