### ISSUE TITLE
enclose trying to add directories outside project folder

### ISSUE THREAD

**Issue by balasivagnanam** [igorklopov/enclose#147]
My project files are in C\Codes\momtest0.5-enclose and I am running
`C:\Codes\momtest0.5-enclose>enclose compile.js --config config.js --loglevel info`

my compile.js:
```
"use strict";

var flags = [];
var enclose = require("enclose").exec;
flags.push("--config", "./config.js");
flags.push("./server.js");
enclose(flags);
```

My config.js
```
"use strict";
module.exports = {
  assets: "./portal/**",
  dirs: [ "./portal",
          "./contributions",
          "./images",
          "./libraries",
          "./portal",
          "./temp-files"
         ]
};
```
Not sure why it is trying to add C:\ to my executable. And because of that it gives empty string error.
```
c:\Codes\momtest0.5-enclose\node_modules
  info  The directory listing was included into executable (1 item)

c:\
  info  The directory listing was included into executable (1 item)
undefined:0



RangeError: Invalid string length
    at Array.join (native)
    at console.c:\thebox\enclose-inside\lib\generate.js.module.exports (e:0)
    at e:0
    at fn (c:\thebox\enclose-inside\node_modules\async\lib\async.js:746:34)
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:1213:16
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:166:37
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:706:43
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:167:37
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:1209:30
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:52:16

C:\Codes\momtest0.5-enclose>
```

**Comment by igorklopov** [comment]
Please do any of the following:
1) Run your compile.js directly (`node compile.js`)
2) Run `enclose server.js --config config.js --loglevel info`
Not both. You are trying to compile the compilation script.

**Comment by balasivagnanam** [comment]
still getting some error.


```
C:\Codes\momtest0.5-enclose>node compile.js

c:\Codes\momtest0.5-enclose\node_modules\natives\index.js
  warning  Cannot resolve 'id'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
undefined:0



RangeError: Invalid string length
    at Array.join (native)
    at console.c:\thebox\enclose-inside\lib\generate.js.module.exports (e:0)
    at e:0
    at fn (c:\thebox\enclose-inside\node_modules\async\lib\async.js:746:34)
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:1213:16
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:166:37
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:706:43
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:167:37
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:1209:30
    at c:\thebox\enclose-inside\node_modules\async\lib\async.js:52:16
```

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
