### ISSUE TITLE
[name of script] was not included into executable at compilation stage. Please recompile adding it as asset or script.

### ISSUE THREAD

**Issue by maxgalbu** [igorklopov/enclose#159]
```
$ enclose versioning.js
$ ./versioning
*** Evaluation version. Please subscribe to full version.
module.js:550
  module._compile(internalModule.stripBOM(content), filename);
         ^

Error: File '/home/vagrant/home/vagrant/library/versioning' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at Error (native)
    at Object.console./thebox/home/vagrant/library/versioning.js.dev (e:0)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```
Something's wrong with the path... `/home/vagrant/home/vagrant/` is incorrect

Centos 7.2
Node 6.10.1

**Comment by maxgalbu** [comment]
Sorry, it was an issue with my code
