### ISSUE TITLE
Windows install failing

### ISSUE THREAD

**Issue by CraigLager** [igorklopov/enclose#162]
Tried multiple times, always the same error:

```
Error: 403,https://enclosejs.s3.amazonaws.com/enclose-v0.12.15-win32-5c54091.exe.sha256
    at ClientRequest.<anonymous> (C:\Users\Craig\AppData\Roaming\npm\node_modules\enclose\postinstall.js:41:25)

    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:421:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:311:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "enclose"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! enclose@2.2.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the enclose@2.2.0 postinstall script 'node postinstall.js'.
npm ERR! This is most likely a problem with the enclose package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls enclose
npm ERR! There is likely additional logging output above.
```

**Comment by usamaazhar** [comment]
facing same issue

**Comment by george-kar** [comment]
same here

**Comment by Tjommel** [comment]
+1

**Comment by FriendlyNGeeks** [comment]
@Tjommel  , @george-kar  , @usamaazhar  , @CraigLager  kept looking found the new package as enclose is no long maintained [https://github.com/zeit/pkg](https://github.com/zeit/pkg)

**Comment by ramtinsoltani** [comment]
Same here:
```
npm install enclose

> enclose@2.2.0 postinstall P:\Practice\js\proxy\node_modules\enclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v0.12.15-win32-5c54091.exe ...
P:\Practice\js\proxy\node_modules\enclose\postinstall.js:165
    throw error;
    ^

Error: 403,https://enclosejs.s3.amazonaws.com/enclose-v0.12.15-win32-5c54091.exe.sha256
    at ClientRequest.<anonymous> (P:\Practice\js\proxy\node_modules\enclose\postinstall.js:41:25)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
npm WARN proxy@1.0.0 No description
npm WARN proxy@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! enclose@2.2.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the enclose@2.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ramtin\AppData\Roaming\npm-cache\_logs\2017-11-27T21_45_18_506Z-debug.log
```

**Comment by daviidmart** [comment]
same

**Comment by ulvido** [comment]
+1

**Comment by Shaukat456** [comment]
Was facing the same issue , turns out that Enclose.js is not maintained anymore! An alternate to this could be npm **pkg package name is pkg**    you can install it via `npm i pkg`.
