### ISSUE TITLE
403 error when installing

### ISSUE THREAD

**Issue by Celadora** [igorklopov/enclose#163]
when installing from npm using:
```
sudo npm install enclose -g

```

The following error occurs:

```
/usr/local/bin/enclose -> /usr/local/lib/node_modules/enclose/bin/enclose.js

> enclose@2.2.0 postinstall /usr/local/lib/node_modules/enclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v0.12.15-linux-x86-c225585 ...
/usr/local/lib/node_modules/enclose/postinstall.js:165
    throw error;
    ^

Error: 403,https://enclosejs.s3.amazonaws.com/enclose-v0.12.15-linux-x86-c225585.sha256
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/enclose/postinstall.js:41:25)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! enclose@2.2.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the enclose@2.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-10-13T04_09_06_626Z-debug.log

```

The underlying object on AWS S3 might need to be set to public.

**Comment by testacode** [comment]
Having the same issue, this package is unusable... fuck

**Comment by igorklopov** [comment]
Please switch to https://github.com/zeit/pkg. EncloseJS is not maintained anymore. All improvements go to pkg.
