### ISSUE TITLE
Can't install on Debian ARM 

### ISSUE THREAD

**Issue by dimraft** [igorklopov/enclose#164]
I'm trying to install on Debian 8 ARM (Raspbian).
I'm new to npm, so I might have missed something.

The error I get is:

```
$ sudo npm install -g enclose
/usr/local/bin/enclose -> /usr/local/lib/node_modules/enclose/bin/enclose.js

> enclose@2.2.0 postinstall /usr/local/lib/node_modules/enclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v4.4.7-linux-armv7-c225585 ...
/usr/local/lib/node_modules/enclose/postinstall.js:165
    throw error;
    ^

Error: 403,https://enclosejs.s3.amazonaws.com/enclose-v4.4.7-linux-armv7-c225585.sha256
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/enclose/postinstall.js:41:25)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:433:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:97:23)
    at TLSSocket.socketOnData (_http_client.js:322:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
npm WARN This failure might be due to the use of legacy binary "node"
```

Is the issue here likely to be with Enclose's compatibility with Raspbian, or with my environment?

**Comment by scott-nightingale** [comment]
help! same issue

**Comment by BurakDev** [comment]
enclose isn't maintened anymore, switch to https://github.com/zeit/pkg
