### ISSUE TITLE
can't install on macosx high sierra 10.13.1

### ISSUE THREAD

**Issue by jusurb** [igorklopov/enclose#165]
```
npm install -g enclose
/usr/local/bin/enclose -> /usr/local/lib/node_modules/enclose/bin/enclose.js

> enclose@2.2.0 postinstall /usr/local/lib/node_modules/enclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v0.12.15-darwin-x64-c225585 ...
/usr/local/lib/node_modules/enclose/postinstall.js:165
    throw error;
    ^

Error: 403,https://enclosejs.s3.amazonaws.com/enclose-v0.12.15-darwin-x64-c225585.sha256
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/enclose/postinstall.js:41:25)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! enclose@2.2.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the enclose@2.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2017-11-15T09_58_12_825Z-debug.log
```
npm: 5.5.1
node: 8.9.1

**Comment by kgdiem** [comment]
Getting the same exact issue on Windows 10. 

Node: 8.2.1
NPM: 5.3.0

**Comment by ZAYEC77** [comment]
Hey guys.
Check first lines from the readme:
This project is deprecated
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg.
