### ISSUE TITLE
Can't install on Linux

### ISSUE THREAD

**Issue by ThatOneCalculator** [igorklopov/enclose#171]
- OS: Arch Rolling x86_64
- Command issued: `npm i -g enclose`
- Error:
```
/home/kainoa/.npm-global/bin/enclose -> /home/kainoa/.npm-global/lib/node_modules/enclose/bin/enclose.js

> enclose@2.2.0 postinstall /home/kainoa/.npm-global/lib/node_modules/enclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v0.12.15-linux-x86-c225585 ...
/home/kainoa/.npm-global/lib/node_modules/enclose/postinstall.js:165
    throw error;
    ^

Error: 403,https://enclosejs.s3.amazonaws.com/enclose-v0.12.15-linux-x86-c225585.sha256
    at ClientRequest.<anonymous> (/home/kainoa/.npm-global/lib/node_modules/enclose/postinstall.js:41:25)
    at Object.onceWrapper (node:events:486:26)
    at ClientRequest.emit (node:events:379:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:636:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
    at TLSSocket.socketOnData (node:_http_client:502:22)
    at TLSSocket.emit (node:events:379:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:227:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! enclose@2.2.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the enclose@2.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kainoa/.npm/_logs/2021-01-28T00_23_58_710Z-debug.log

~   pls npm i -g enclose
[sudo] password for kainoa:        
Sorry, try again.
[sudo] password for kainoa:       
/usr/bin/enclose -> /usr/lib/node_modules/enclose/bin/enclose.js

> enclose@2.2.0 postinstall /usr/lib/node_modules/enclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v0.12.15-linux-x86-c225585 ...
/usr/lib/node_modules/enclose/postinstall.js:165
    throw error;
    ^

Error: 403,https://enclosejs.s3.amazonaws.com/enclose-v0.12.15-linux-x86-c225585.sha256
    at ClientRequest.<anonymous> (/usr/lib/node_modules/enclose/postinstall.js:41:25)
    at Object.onceWrapper (node:events:486:26)
    at ClientRequest.emit (node:events:379:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:636:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
    at TLSSocket.socketOnData (node:_http_client:502:22)
    at TLSSocket.emit (node:events:379:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:227:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! enclose@2.2.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the enclose@2.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-28T00_24_09_228Z-debug.log
```
- Going to https://enclosejs.s3.amazonaws.com/enclose-v0.12.15-linux-x86-c225585.sha256 in browser shows a 403 error.

**Comment by alejosv** [comment]
Same issue:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

**Comment by vervoortkobe** [comment]
Having the same issue on Windows... :/

**Comment by Gkiokan** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/7249224/166452762-e24cc384-45c4-44f0-9848-dc976233b5dc.png">

Same error in 2022. Still http error 403 on the install package.

**Comment by ThatOneCalculator** [comment]
Honestly safe to assume this project is dead in the water, and there are better solutions now anyways.

**Comment by ThatOneCalculator** [comment]
Oh yea, not to mention:

![Screenshot_20220503-103029_1.png](https://user-images.githubusercontent.com/44733677/166507170-67b33c0d-f23c-43ca-a065-eac0707e8f34.png)
