### ISSUE TITLE
Why "thebox"?

### ISSUE THREAD

**Issue by marinasundstrom** [igorklopov/enclose#54]
I'm currently experimenting with enclose in an effort to compile a commercial product. However, I have encountered some problems and can't continue the evaluation. 

My main obstacle: "thebox"

Why are you adding "thebox" in paths?

**Comment by k1ng440** [comment]
i have same question

**Comment by igorklopov** [comment]
If you encounter "thebox" then you must use `__dirname` or `__filename` somewhere in your code. Read Packaging carefully: https://github.com/igorklopov/enclose/wiki/02.Packaging . Also you can post the full error here.

**Comment by hanhealthy** [comment]
I got same error, any ideas?

I2cReader processed error exit, fork another I2cReader process
**\* Evaluation version. Please subscribe to full version.
undefined:0

Error: Could not find module root given file: "/thebox/home/pi/enclose/examples/Reader1/node_modules". Do you have a `package.json` file? 
    at Function.getRoot (e:0)
    at bindings (e:0)
    at Object.console.+/+t+h+e+b+o+x+/+h+o+m+e+/+p+i+/+e+n+c+l+o+s+e+/+e+x+a+m+p+l+e+s+/+R+e+a+d+e+r+1+/+n+o+d+e+_+m+o+d+u+l+e+s+/+e+p+o+l+l+/+e+p+o+l+l+.+j+s.dev (e:0)
    at r (e:0)
    at P (e:0)
    at f (e:0)
    at Object.console.+/+t+h+e+b+o+x+/+h+o+m+e+/+p+i+/+e+n+c+l+o+s+e+/+e+x+a+m+p+l+e+s+/+R+e+a+d+e+r+1+/+n+o+d+e+_+m+o+d+u+l+e+s+/+r+p+i+-+g+p+i+o+/+r+p+i+-+g+p+i+o+.+j+s.dev (e:0)
    at r (e:0)
    at P (e:0)
    at f (e:0)

**Comment by rldcampbell** [comment]
I have the same issue (using full version of enclose), and I do **not** use `__dirname` or `__filename` anywhere, only `process.cwd()`. This is only a problem for me when compiling for 32 bit using `enclose -a x86`. The error I see is:

```
module.js:440
    var err = new Error("Cannot find module '" + request + "'");
              ^

Error: Cannot find module 'c:\thebox\Projects\node\node_modules\sqlite3\lib\binding\node-v48-win32-ia32\node_sqlite3.node'
1) If you want to enclose the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to enclose the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.argv[1].
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\thebox\Projects\node\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

In my code I use: 

```
sqlite3 = require(process.cwd() + '/bin/node_modules/sqlite3');
```

Any ideas?  A quick fix or workaround would be great.  Many thanks

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
