### ISSUE TITLE
child_process.fork is not supported yet

### ISSUE THREAD

**Issue by fuatsengul** [igorklopov/enclose#61]
Hello,
I saw this error message after packaging my project with enclose.
Is there any way to run this project with fork as enclosed? Or can I exclude fork-relevant parts from packaging and keep packaged other parts? This is an application that needs commercial secrecy, and my deadline is very near :/ needing some advise.

Thanks, fuat

**Comment by igorklopov** [comment]
Please give error message. I don't see it. Does your application call `fork`?

**Comment by JoyKrishnaMondal** [comment]
Hey !
I have a similar error on Linux I think - It works fine on Windows ! 
![untitled2](https://cloud.githubusercontent.com/assets/3383928/10247068/2776c35e-690e-11e5-9925-8bf4f303e8ec.png)

**Comment by fuatsengul** [comment]
yes my app calls `fork`
I'm using it on raspberry pi(raspbian, sort of debian)

**Comment by fuatsengul** [comment]
Here is the log:

```
Error: EncloseJS: Fork is not supported yet
    at Math.Enclose.+s+t+u+b+:+/+/+c+h+i+l+d+_+p+r+o+c+e+s+s.cp.fork (<anonymous>)
    at Math.Enclose.+/+t+h+e+b+o+x+/+v+a+r+/+a+p+p+s+/+f+s+-+n+e+t+w+o+r+k+-+c+l+i+e+n+t+/+l+i+b+/+f+s+_+v+m+.+m+i+n+.+j+s.AsteroidVM.fork (<anonymous>)
    at Math.Enclose.+/+t+h+e+b+o+x+/+v+a+r+/+a+p+p+s+/+f+s+-+n+e+t+w+o+r+k+-+c+l+i+e+n+t+/+l+i+b+/+f+s+_+v+m+.+m+i+n+.+j+s.AsteroidVM.run (<anonymous>)
    at Math.Enclose.+/+t+h+e+b+o+x+/+v+a+r+/+a+p+p+s+/+f+s+-+n+e+t+w+o+r+k+-+c+l+i+e+n+t+/+l+i+b+/+f+s+_+c+l+i+e+n+t+.+m+i+n+.+j+s.AsteroidClient._codeUpdated (<anonymous>)
    at <anonymous>
    at <anonymous>
    at Array.forEach (native)
    at Function.Math.Enclose.+/+t+h+e+b+o+x+/+v+a+r+/+a+p+p+s+/+f+s+-+n+e+t+w+o+r+k+-+c+l+i+e+n+t+/+n+o+d+e+_+m+o+d+u+l+e+s+/+d+d+p+/+n+o+d+e+_+m+o+d+u+l+e+s+/+d+d+p+-+u+n+d+e+r+s+c+o+r+e+-+p+a+t+c+h+e+d+/+u+n+d+e+r+s+c+o+r+e+.+j+s._.each._.forEach (<anonymous>)
    at Math.Enclose.+/+t+h+e+b+o+x+/+v+a+r+/+a+p+p+s+/+f+s+-+n+e+t+w+o+r+k+-+c+l+i+e+n+t+/+n+o+d+e+_+m+o+d+u+l+e+s+/+d+d+p+/+l+i+b+/+d+d+p+-+c+l+i+e+n+t+.+j+s.DDPClient._message (<anonymous>)
    at null.<anonymous> (<anonymous>)
    at emit (events.js:107:17)
    at Math.Enclose.+/+t+h+e+b+o+x+/+v+a+r+/+a+p+p+s+/+f+s+-+n+e+t+w+o+r+k+-+c+l+i+e+n+t+/+n+o+d+e+_+m+o+d+u+l+e+s+/+d+d+p+/+n+o+d+e+_+m+o+d+u+l+e+s+/+f+a+y+e+-+w+e+b+s+o+c+k+e+t+/+l+i+b+/+f+a+y+e+/+w+e+b+s+o+c+k+e+t+/+a+p+i+/+e+v+e+n+t+_+t+a+r+g+e+t+.+j+s.EventTarget.dispatchEvent (<anonymous>)
    at Math.Enclose.+/+t+h+e+b+o+x+/+v+a+r+/+a+p+p+s+/+f+s+-+n+e+t+w+o+r+k+-+c+l+i+e+n+t+/+n+o+d+e+_+m+o+d+u+l+e+s+/+d+d+p+/+n+o+d+e+_+m+o+d+u+l+e+s+/+f+a+y+e+-+w+e+b+s+o+c+k+e+t+/+l+i+b+/+f+a+y+e+/+w+e+b+s+o+c+k+e+t+/+a+p+i+.+j+s.instance._receiveMessage (<anonymous>)
    at null.<anonymous> (<anonymous>)
    at emit (events.js:129:20)
    at null.<anonymous> (<anonymous>)
```

**Comment by igorklopov** [comment]
Enclose 2.0.0 is just released. `child_process.fork` is fully supported now. Please try again and give your feedback. Thanks!

**Comment by fuatsengul** [comment]
Thanks
