### ISSUE TITLE
Error when execute "enclose" or "enclose --help"

### ISSUE THREAD

**Issue by mrbigmouth** [igorklopov/enclose#65]
~# enclose --help
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/enclose/bin/enclose-v0.12.7-linux-x86-3a4e2f6 ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3

environment: Ubuntu 14.04.1 64bit

**Comment by igorklopov** [comment]
I removed `--help` in 1.0.0. Just run `enclose` to see CLI options. Thanks!
