### ISSUE TITLE
I2c-bus and rpi-gpio support in raspberry pi

### ISSUE THREAD

**Issue by hanhealthy** [igorklopov/enclose#81]
Hi, when I package code contain i2c-bus and rpi-gpio, got eror like this :

**\* Evaluation version. Please subscribe to full version.
undefined:0

Error: Could not find module root given file: "/thebox/home/pi/enclose/examples/Reader1/node_modules". Do you have a `package.json` file? 
    at Function.getRoot (e:0)
    at bindings (e:0)
    at Object.console.+/+t+h+e+b+o+x+/+h+o+m+e+/+p+i+/+e+n+c+l+o+s+e+/+e+x+a+m+p+l+e+s+/+R+e+a+d+e+r+1+/+n+o+d+e+_+m+o+d+u+l+e+s+/+e+p+o+l+l+/+e+p+o+l+l+.+j+s.dev (e:0)
    at r (e:0)
    at P (e:0)
    at f (e:0)
    at Object.console.+/+t+h+e+b+o+x+/+h+o+m+e+/+p+i+/+e+n+c+l+o+s+e+/+e+x+a+m+p+l+e+s+/+R+e+a+d+e+r+1+/+n+o+d+e+_+m+o+d+u+l+e+s+/+r+p+i+-+g+p+i+o+/+r+p+i+-+g+p+i+o+.+j+s.dev (e:0)
    at r (e:0)
    at P (e:0)
    at f (e:0)

why there is " thebox" in the front ???

Thanks

**Comment by scramble45** [comment]
Same problem here.

**Comment by igorklopov** [comment]
Confirm. Will be fixed in 2.1.0.

**Comment by scramble45** [comment]
We were looking forward to this in 2.0.0, any idea when 2.1.0 will be ready?

**Comment by igorklopov** [comment]
@scramble45  Please try now with 2.0.1. The fix is there.

**Comment by daohuuthao** [comment]
I install enclose in Raspberry Pi,
when i run : enclose -v

/usr/lib/node_modules/enclose/bin/enclose.js:126
      if (error) throw error;
                       ^
Error: Compiler not found for v4.4.2-linux-armv7
    at ChildProcess.<anonymous> (/usr/lib/node_modules/enclose/bin/enclose.js:188:19)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:818:12)
root@orangepi:/var/local/BanCa# npm install -g enclose
/usr/bin/enclose -> /usr/lib/node_modules/enclose/bin/enclose.js

> enclose@2.0.2 postinstall /usr/lib/node_modules/enclose
> node postinstall.js

Killed

**Comment by igorklopov** [comment]
Try running just `enclose` instead of `enclose -v`

**Comment by igorklopov** [comment]
Also you may try `npm install -g enclose --unsafe-perm`

**Comment by scramble45** [comment]
When just adding the require for rpi-gpio, this is what I get.

undefined:0

TypeError: Cannot read property 'h' of null
    at e:0
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/thebox/node_code/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/thebox/node_code/node_modules/epoll/epoll.js:1:99)

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
